In [1]:
import json
import requests
import numpy as np
import pandas as pd

from transformers import BertTokenizer

df = pd.read_excel('datasets/dataset_turnbackhoax_summarized.xlsx')
df = df[['cleaned', 'label']]

c:\Users\LENOVO\GitHub\bangkit_capstone\VENU-ML\HOAX_DETECTION\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [35]:
df_test = df.sample()

# df_test.cleaned.values
len(df_test['cleaned'].values[0].split())

11

In [36]:
tokenizer = BertTokenizer.from_pretrained('indobenchmark/indobert-lite-base-p1')

max_len = 70

tokenized = tokenizer(
    text=df_test['cleaned'].tolist(),
    add_special_tokens=True,
    max_length=max_len,
    truncation=True,
    padding='max_length',
    return_tensors='tf',
    return_token_type_ids=False,
    return_attention_mask=True,
)

tokenized

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'AlbertTokenizer'. 
The class this function is called from is 'BertTokenizer'.


{'input_ids': <tf.Tensor: shape=(1, 70), dtype=int32, numpy=
array([[    2,  2641,  9642, 29945,  9286, 12160, 29859, 29947,  4287,
         1909, 29947, 11808,  8165,   154,  2318,  1225,  4310, 23113,
        29081, 20944,  4235, 29848,     3,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(1, 70), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]])>}

In [37]:
X1 = np.squeeze(tokenized['attention_mask']._numpy())
X2 = np.squeeze(tokenized['input_ids']._numpy())


In [38]:
data1 = json.dumps({"signature_name": "serving_default",
                   "instances": [{'attention_mask':X1.tolist(),'input_ids':X2.tolist()}]})
# both x and y are numpy 2d array 

json_response = requests.post('http://localhost:8501/v1/models/NLP:predict',
                               data=data1)

pred = json.loads(json_response.text)

print(pred)

{'predictions': [[0.99728781]]}


In [20]:
!saved_model_cli show --dir C:/Users/LENOVO/GitHub/bangkit_capstone/VENU-ML/HOAX_DETECTION/test_deploy/model/1 --all


MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['attention_mask'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 70)
        name: serving_default_attention_mask:0
    inputs['input_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 70)
        name: serving_default_input_ids:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['dense_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predic

2023-12-10 10:04:53.302482: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "c:\users\lenovo\github\bangkit_capstone\venu-ml\hoax_detection\venv\lib\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 92, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:/Users/LENOVO/GitHub/bangkit_capstone/VENU-ML/HOAX_DETECTION/test_deploy/model/2\variables\variables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lenovo\github\bangkit_capstone\venu-ml\hoax_detection\venv\lib\


MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['attention_mask'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 70)
        name: serving_default_attention_mask:0
    inputs['input_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 70)
        name: serving_default_input_ids:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['dense_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predic